OUTPUT = output
arg = some

a: a.cpp
	g++ a.cpp -o $(OUTPUT)

b: b.cpp
	g++ b.cpp -o $(OUTPUT)

c: c.cpp
	g++ c.cpp -o $(OUTPUT)

d: d.cpp
	g++ d.cpp -o $(OUTPUT)

e: e.cpp
	g++ e.cpp -o $(OUTPUT)

f: f.cpp
	g++ f.cpp -o $(OUTPUT)

some: $(arg).cpp
	g++ $(arg).cpp -o $(OUTPUT)
